# ¡Bienvenidos a la segunda semana del Mastery Data Science!

### Temas de la segunda semana:
* NumPy
* Pandas

### Objetivos de la sesión 1 semana 2: 

* Conocer las ventajas de utilizar los arreglos de NumPy
* Utilizar y las operaciones básicas de NumPy 
* Localizar posibles aplicaciones 

# 1. Calentando motores

El objetivo de esta sección es realizar una serie de ejercicios que servirán para más adelante comparar  la optimizada velocidad de NumPy contra las listas de Python.

## 1.1 Ejercicios

Usando lo aprendido la semana pasada, realicemos los siguientes ejercicios

1.   Crea un vector con 100 números aleatorios uniformemente distribuidos en el intervalo comprendido entre el -1 y 1

2.   Crea un vector que multiplique por 10 cada elemento del vector creado en el ejercicio 1.

3.   Crea una matriz que tenga 10 filas y 10 columnas con 100 números aleatorios entre -1 y 1. Puedes convertir tu vector anterior en una matriz.

4.   Imprime la tercer columna de la matriz creada en el ejercicio 3.

5.   Imprime la media de la tercer columna de la matriz creada en el ejercicio 3.

6.   Imprime el valor máximo y mínimo de la 8va columna de la matriz creada en el ejercicio 3.

7.   Crea un vector del 1 al 5 y eleva a la potencia 3 cada elemento.

8.   Del vector creado en el ejercicio 7 y muestra la raíz cuadrada.

9.   Calcular el producto punto de los siguientes dos vectores: [1,2,3] y [3,2,1]

## 1.2 Soluciones

¿Ya terminaste? Compara tus resultados

### 1.   Crea un vector con 100 números aleatorios uniformemente distribuidos en el intervalo comprendido entre el -1 y 1

In [0]:
# Importamos la libreria necesaria 
import random

# Definicion del vector
random_vector = [random.uniform(-1,1) for i in range(100)]

# Impresión de los valores obtenidos
print(random_vector)
print()
print(len(random_vector))

[0.8241934363487131, 0.21139621212418924, -0.23238582428106702, 0.5738654311814013, -0.022491853379238202, -0.2686139647595127, 0.7307813496366544, 0.2806285359562477, 0.3961829057717363, 0.5080652961034544, -0.9427313726200095, -0.020104470494571425, -0.7369795438925058, -0.2904888129756731, 0.26099962414510136, -0.2792106875875058, 0.8721997081753741, 0.2080641986386953, -0.4178927522262541, 0.2254398715893331, -0.16208366912256267, -0.43070858736334006, -0.9994182362734156, 0.4784665204669112, 0.2514363470980625, -0.8279116368169084, 0.9414902657506894, -0.4772897742299307, -0.27949491914409763, -0.4613203066997402, 0.5734145815509859, 0.549314902691068, -0.8533892159550827, 0.7493829433548813, -0.723784687605175, -0.20345625692377967, -0.5497214126218442, -0.6525391341463498, -0.9341348172054567, 0.7535309365449945, 0.17028649585012667, -0.6989201872155382, 0.9794331626696053, 0.4163382029240119, -0.9746720502414019, -0.7011858360759227, -0.4824849740279469, 0.5979212424766505, -0.

 ### 2.  ** Crea un vector que multiplique por 10 cada elemento del vector creado en el ejercicio 1.**

In [0]:
# Multiplicamos cada elemento contenido en random_vector por 10 
random_vector_10 = [i * 10 for i in random_vector]

#Mostramos el resultado
print(random_vector_10)

[8.24193436348713, 2.1139621212418924, -2.32385824281067, 5.738654311814013, -0.22491853379238202, -2.686139647595127, 7.307813496366544, 2.806285359562477, 3.961829057717363, 5.080652961034544, -9.427313726200095, -0.20104470494571425, -7.369795438925058, -2.904888129756731, 2.6099962414510136, -2.792106875875058, 8.721997081753742, 2.080641986386953, -4.178927522262541, 2.254398715893331, -1.6208366912256267, -4.307085873633401, -9.994182362734156, 4.784665204669112, 2.514363470980625, -8.279116368169085, 9.414902657506893, -4.772897742299307, -2.7949491914409763, -4.613203066997402, 5.734145815509859, 5.49314902691068, -8.533892159550827, 7.493829433548813, -7.23784687605175, -2.0345625692377967, -5.4972141262184415, -6.525391341463498, -9.341348172054566, 7.535309365449945, 1.7028649585012667, -6.989201872155382, 9.794331626696053, 4.163382029240119, -9.74672050241402, -7.011858360759227, -4.824849740279468, 5.979212424766505, -5.449229897697223, -8.296019346553924, -0.857502214166

### 3. Crea una matriz que tenga 10 filas y 10 columnas con 100 números aleatorios entre -1 y 1.

In [0]:
# No hay matrices, pero existen listas de listas
matriz_100 = []

for i in range(10):
  matriz_100.append(random_vector[10*i:10*i+10])

print(matriz_100)

[[0.8241934363487131, 0.21139621212418924, -0.23238582428106702, 0.5738654311814013, -0.022491853379238202, -0.2686139647595127, 0.7307813496366544, 0.2806285359562477, 0.3961829057717363, 0.5080652961034544], [-0.9427313726200095, -0.020104470494571425, -0.7369795438925058, -0.2904888129756731, 0.26099962414510136, -0.2792106875875058, 0.8721997081753741, 0.2080641986386953, -0.4178927522262541, 0.2254398715893331], [-0.16208366912256267, -0.43070858736334006, -0.9994182362734156, 0.4784665204669112, 0.2514363470980625, -0.8279116368169084, 0.9414902657506894, -0.4772897742299307, -0.27949491914409763, -0.4613203066997402], [0.5734145815509859, 0.549314902691068, -0.8533892159550827, 0.7493829433548813, -0.723784687605175, -0.20345625692377967, -0.5497214126218442, -0.6525391341463498, -0.9341348172054567, 0.7535309365449945], [0.17028649585012667, -0.6989201872155382, 0.9794331626696053, 0.4163382029240119, -0.9746720502414019, -0.7011858360759227, -0.4824849740279469, 0.597921242476

In [0]:
# Visualización como matriz
for i in range(10):
  print(matriz_100[i])

[0.8241934363487131, 0.21139621212418924, -0.23238582428106702, 0.5738654311814013, -0.022491853379238202, -0.2686139647595127, 0.7307813496366544, 0.2806285359562477, 0.3961829057717363, 0.5080652961034544]
[-0.9427313726200095, -0.020104470494571425, -0.7369795438925058, -0.2904888129756731, 0.26099962414510136, -0.2792106875875058, 0.8721997081753741, 0.2080641986386953, -0.4178927522262541, 0.2254398715893331]
[-0.16208366912256267, -0.43070858736334006, -0.9994182362734156, 0.4784665204669112, 0.2514363470980625, -0.8279116368169084, 0.9414902657506894, -0.4772897742299307, -0.27949491914409763, -0.4613203066997402]
[0.5734145815509859, 0.549314902691068, -0.8533892159550827, 0.7493829433548813, -0.723784687605175, -0.20345625692377967, -0.5497214126218442, -0.6525391341463498, -0.9341348172054567, 0.7535309365449945]
[0.17028649585012667, -0.6989201872155382, 0.9794331626696053, 0.4163382029240119, -0.9746720502414019, -0.7011858360759227, -0.4824849740279469, 0.5979212424766505,

### 4. Imprime la tercer columna de la matriz creada en el ejercicio 3

In [0]:
#Si usamos un solo índice obtenemos solo la fila 
print('La primera fila de la matriz es:')
print(matriz_100[0])
print()


# La tercera columna representa el tercer elemento de cada fila 
ter_col=[matriz_100[i][2] for i in range(10)]
print('La tercera columna es:')
print(ter_col)


La primera fila de la matriz es:
[0.8241934363487131, 0.21139621212418924, -0.23238582428106702, 0.5738654311814013, -0.022491853379238202, -0.2686139647595127, 0.7307813496366544, 0.2806285359562477, 0.3961829057717363, 0.5080652961034544]

La tercera columna es:
[-0.23238582428106702, -0.7369795438925058, -0.9994182362734156, -0.8533892159550827, 0.9794331626696053, -0.39127565452197466, -0.4508002417212478, -0.38053061635557484, 0.6378315119259272, -0.321190684114913]


### 5.   Imprime la media de la tercer columna de la matriz creada en el ejercicio 3.

In [0]:
# Usando las funciones basicas
media=sum(ter_col)/len(ter_col)

print('La media es igual a ' +str(media))

print()

# Importando el paquete statistics de 
import statistics as st
print('La media es igual a ' +str(st.mean(ter_col)))

La media es igual a -0.2748705342520249

La media es igual a -0.2748705342520249


### 6. Imprime el valor máximo y mínimo de la 8 columna de la matriz creada en el ejercicio 3.

In [0]:
# Selección de columna 
oct_col=[matriz_100[i][7] for i in range(10)]

print('El valor máximo de la octava columna es '+str(max(oct_col))+' mientras que el mínimo es '+str(min(oct_col)))


El valor máximo de la octava columna es 0.8530033544276612 mientras que el mínimo es -0.6525391341463498


### 7.   Crea un vector del 1 al 5 y eleva a la potencia 3 cada elemento.

In [0]:
# Creación del vector que contiene del 1 al 5 
vector=list(range(1,6))
print('El vector es: '+str(vector))
print()

# Elevación al cuadrado de cada uno de los elementos 
vector1=[vector[i]**3 for i in range(5) ]
print('El vector es: '+str(vector1))

El vector es: [1, 2, 3, 4, 5]

El vector es: [1, 8, 27, 64, 125]


### 8.   Del vector creado en el ejercicio 7 y muestra la raíz cuadrada.

In [0]:
sqrt_vector1=[vector1[i]**(1/2) for i in range(5)]
print(sqrt_vector1)

[1.0, 2.8284271247461903, 5.196152422706632, 8.0, 11.180339887498949]


### 9.   Calcular el producto punto de los siguientes dos vectores:  [1,2,3] y  [3,2,1]

In [0]:
# Definimos los vectores a usar 
a = [1,2,3]
b = [3,2,1]

# Usando tuplas y un ciclo
punto = 0
for e, f in zip(a,b):
  punto += e*f
print('El producto punto es '+str(punto))
print()

# Usando List comprehensions 
punto2=sum([a[i]*b[i] for i in range(len(a))])
print('El producto punto es '+str(punto2))

El producto punto es 10

El producto punto es 10


## 1.3 ¿Cómo les fue?
* ¿Difícil?
* ¿Laborioso?
* ¿Cómo podría ser más fácil?

# 2. Numerical Python (NumPy)


*Numpy* o *Numertical Python* es un paquete fundamental sobre el cual estan construidos muchos de los paquetes de ciencia de datos más utilizados. Su elemento fundamental son los *arrays* (arreglos) los cuales toman características operacionales similares a las matrices y vectores de álgebra lineal. 

Algunas operaciones que se pueden realizar: sumar, restar, multiplicar, producto punto, inversa de una matriz, sistemas lineales, etc.

¿Recuerdas los siguientes conceptos?
* Vector
* Matriz




### 2.1 ¿Cómo usamos Numpy?

Lo estándar es importar el paquete y renombrarlo (apodarlo) *np**

In [0]:
import numpy as np

### 2.2 ¿Qué es un vector?

Un vector es... 
- Conjunto de elementos del mismo tipo
- Matriz unidimensional
- Mutable

La manera más fácil de crear un arreglo es convertir a partir de una lista predeterminada usando el comando `array`

In [0]:
#Arreglo unidimensional 
arreglo=np.array([3, 33, 333])
print(arreglo)
print()

# Método shape 
print(arreglo.shape) 
print()

# Método size
print(arreglo.size)


Ahora definamos un arreglo bidimensional, algo parecido a una matriz: ahora tenemos renglones y columnas. 

De igual manera podemos definirlo de igual manera con el comando `array` y una serie de listas que seran interpretadas como las filas de nuestros arreglos

In [0]:
#Arreglo bidimensional
arreglo2D=np.array([[11,12,13],[21,22,23]])
print(arreglo2D)
print()

# Método shape 
print(arreglo2D.shape) 
print()

# Método size
print(arreglo2D.size)
print()

print(arreglo2D.ndim)


#### Antes de seguir unas preguntas 

* ¿diferencias entre `shape` y `size`? 

* ¿que se indica primero en `shape`: el número de columnas o el numero de filas?


Ahora exploremos algunos tipos de arreglos preeterminados: busquemos como generar de manera rápida mendiante funciones de NumPy los siguientes arreglos: 

* únicamente contiene ceros

* únicamente contiene unos 

* únicamente contiene valores iguales a una constante

* que contenga únicamente unos en la diagonal principal y ceros en las demás posiciones

* que sea cuadrado y que contenga únicamente unos en la diagonal principal y ceros en las demás posiciones

* contenga números aleatorios uniformemente distribuidos

* contenga los enteros en un cierto intervalo específico

* contenga N números uniformemente espaciados en un cierto intervalo. 






##### Arreglos preestablecidos

In [0]:
# Arreglo que solo contiene ceros
cero=np.zeros((3,2))
print(cero)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [0]:
# Arreglo que solo contiene ceros
uno=np.ones((2,3))
print(uno)

[[1. 1. 1.]
 [1. 1. 1.]]


In [0]:
# Arreglo que contiene un valores constantes
lleno=np.full((3,4),7) 
print(lleno)

In [0]:
# Arrego con unos en la diagonal principal y ceros en las demas posiciones
diag=np.eye(4,3)
print(diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [0]:
# Arreglo cuadrado que contiene unos en la diagonal principal y ceros en las demás posiciones 
ide=np.identity(4)
print(ide)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [0]:
# Arreglo de numeros aleatorios uniformemente distributidos
uni=np.random.random((2,4))
print(uni)

[[0.92064405 0.75334215 0.17675598 0.9007009 ]
 [0.91709836 0.55052545 0.29400042 0.11373483]]


In [0]:
# Arreglo de valores en un rango derminado 
rang=np.arange(3,9)
print(rang)

[3 4 5 6 7 8]


In [0]:
# Arreglo de valores en un intervalo que estan igualmente espaciados
lin=np.linspace(0,4,10)
print(lin)

[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]


In [0]:
# Extra: podemos definir el tipo de dato que contiene nuestro arreglo 
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


### 2.2 Indices

Consideren el siguiente arreglo

In [0]:
Arre = np.array([[11,12,13,14,15,16], [21,22,23,24,25,26], [31,32,33,34,35,36], [41,42,43,44,45,46],[51,52,53,54,55,56],[61,62,63,64,65,66]])
print(Arre)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]
 [51 52 53 54 55 56]
 [61 62 63 64 65 66]]


Podemos seleccionar ciertos datos dentro de un arreglo usando índices de manera semejante a las listas, pero no es igual

In [0]:
# Tercer elemento de la cuarta fila 
a1=Arre[2,3]
print(a1)

34


In [0]:
# Cuarta fila
a2=Arre[3,:]
print(a2)


[41 42 43 44 45 46]


In [0]:
# Quinta columna
a3=Arre[:,5]
print(a3)

[16 26 36 46 56 66]


In [0]:
# Podemos usar listas para especificar los indices de las columnas y filas 

#Elementos deseados 
print(Arre[1,2],Arre[4,5],Arre[5,3],Arre[3,1],Arre[0,5])

#Definición de las filas y columnas
filas=[1,4,5,3,0]
col=  [2,5,3,1,5]

a4=Arre[filas,col]

#Arreglo que contiene los valores específicados
print(a4)




23 56 64 42 16
[23 56 64 42 16]


In [0]:
# De igual manera podemos comparar los elementos de un array y usar el resultado para filtrar 

#Seleccionamos a todos los pares
a5b=Arre % 2==0
print('Arreglo de valores boleanos')
print(a5b)
print()

#Arreglo de los valores dados por el filtro
a5=Arre[a5b]
print(a5)

Arreglo de valores boleanos
[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]

[12 14 16 22 24 26 32 34 36 42 44 46 52 54 56 62 64 66]


### 2.3 Operaciones


#### 2.3.1 Aritmética 

A diferencia de las listas, donde tenemos que hacer algun proceso para operar cada elemento, en los arreglos las operaciones se realizan para cada elemento.

In [0]:
# Creamos unos arreglo para unas pruebas
A=np.arange(10)
B=np.arange(2,12)

print('Arreglo original A=',A)
print('Arreglo original B=',B)
print()

# Suma de un elemento 
print('Suma de una costante ',A+1)
print()

#Suma de arreglos 
print('Suma de arreglos A+B=',A+B)
print()

#Resta
print('Diferencia de arreglos',A-B)
print()


#Multiplicación
print('Multiplicación A*B=',A*B)
print()

#Division
print('Divisio A/B=',A/B)
print()

#Potencias  
print('Elevar el arreglo a la segunda potencia A**2=',A**2)
print()

print('Elevar un numero a la potencia indicada por el arreglo 2**A ',2**A)
print()

print('Elevar un arrelgo a la potencia indicada por el otro arreglo B**A ',B**A)


Arreglo original A= [0 1 2 3 4 5 6 7 8 9]
Arreglo original B= [ 2  3  4  5  6  7  8  9 10 11]

Suma de una costante  [ 1  2  3  4  5  6  7  8  9 10]

Suma de arreglos A+B= [ 2  4  6  8 10 12 14 16 18 20]

Diferencia de arreglos [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]

Multiplicación A*B= [ 0  3  8 15 24 35 48 63 80 99]

Divisio A/B= [0.         0.33333333 0.5        0.6        0.66666667 0.71428571
 0.75       0.77777778 0.8        0.81818182]

Elevar el arreglo a la segunda potencia A**2= [ 0  1  4  9 16 25 36 49 64 81]

Elevar un numero a la potencia indicada por el arreglo 2**A  [  1   2   4   8  16  32  64 128 256 512]

Elevar un arrelgo a la potencia indicada por el otro arreglo B**A  [         1          3         16        125       1296      16807
     262144    4782969  100000000 2357947691]


#### 2.3.2 Estádisticos

Numpy posee las funciones estadísiticas básicas: 
* Media
* Mediana
* Rangos
* Varianzas y covarianzas
* Correlaciones 
* Cuentas

Para mayor información: https://docs.scipy.org/doc/numpy-1.14.5/reference/routines.statistics.html

In [0]:
# Arreglo a usar en esta sección
Arre = np.array([[11,12,13,14,15,16], [21,22,23,24,25,26], [31,32,33,34,35,36], [41,42,43,44,45,46],[51,52,53,54,55,56],[61,62,63,64,65,66]])
print(Arre)
print()

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]
 [51 52 53 54 55 56]
 [61 62 63 64 65 66]]



In [0]:
# Media del arreglo
a1=np.mean(Arre)
print(a1)
print()

# Media de cada una de las filas 
a2=np.mean(Arre,axis=1)
print(a2)
print()

# Mediana del arreglo
a3=np.median(Arre)
print(a3)
print()

# Desviación estándar del arreglo 
a4=np.std(Arre)
print(a4)

38.5

[13.5 23.5 33.5 43.5 53.5 63.5]

38.5

17.163430115607234


In [0]:
# Máximo valor en el arreglo
print('Maximo=',np.amax(Arre))


# Minimo valor en el arreglo 
print('Mínimo=',np.amin(Arre))

# Rango del Arreglo -> R= max(A)-min(A)
print('Rango=',np.ptp(Arre))


Maximo= 66
Mínimo= 11
Rango= 55


#### 2.3.3 Matrices

** Suma de elementos**


In [0]:
A= np.array([[11,12],[21,22]])

print(np.sum(A))

66


In [0]:
print('Suma horizontalmente',np.sum(A,axis=0))
print()
print('Suma verticalmente',np.sum(A,axis=1))

Suma horizontalmente [32 34]

Suma verticalmente [23 43]


**Producto interno**

In [0]:
A1 = np.array([[1,1],[1,1]])
A2 = np.array([[2,2],[2,2]])

print('A1=')
print(A1)
print()
print('A2=')
print(A2)

A1=
[[1 1]
 [1 1]]

A2=
[[2 2]
 [2 2]]


In [0]:
print('Producto interno: ')
print(np.dot(A1,A2))

Producto interno: 
[[4 4]
 [4 4]]


#### 2.3.4 Orden 


In [0]:
# create a 10 element array of randoms
desord = np.random.randn(10)

print(desord)

[-0.48398892  1.01438421  0.31730948  1.26868451 -1.04037194 -1.59547603
  1.39694768  0.68507542 -0.45758873 -0.02027917]


In [0]:
# Crear una copia y ordenarla 
ord = np.array(unsorted)
ord.sort()

print('Desordenados')
print(desord)
print()
print('Ordenados')
print(ord)

[-0.48398892  1.01438421  0.31730948  1.26868451 -1.04037194 -1.59547603
  1.39694768  0.68507542 -0.45758873 -0.02027917]

[-1.52793913 -1.45499634 -0.89802543 -0.75308808 -0.70670147 -0.58191496
 -0.33558558 -0.22843301  0.35877097  1.82234929]


In [0]:
# Obtener los indices que ordenerian el arreglo
ind=desord.argsort()
print('Indices: ',ind)

# Colocamos los indices para que se ordenen 
print(desord[ind])



Indices:  [5 4 0 8 9 2 7 1 3 6]
[-1.59547603 -1.04037194 -0.48398892 -0.45758873 -0.02027917  0.31730948
  0.68507542  1.01438421  1.26868451  1.39694768]


In [0]:
# Encontrando valores únicas

arreglo = np.array([1,2,1,4,2,1,4,2])

print(np.unique(arreglo))

[1 2 4]


#### 2.3.5 Forma 
reshape
transpose 
vstack 
hstack 
contatenados 
ravle 



In [0]:
# Creamos un arreglo unidimensional de 0 al 19
arr = np.arange(20)
print('Original')
print(arr)
print()

# Le cambiamos la forma para que sea un arreglo de 4 x 5 
print('Reacomodo')
ARR=arr.reshape(4,5)
print(ARR)

Original
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reacomodo
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [0]:
# Transposición: cambio de columnas por filas y viceversa
print(ARR.T)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [0]:
# Aplanamos el arreglo de dos dimensiones para que sea de nuevo de uno
print(np.ravel(ARR))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [0]:
#Creamos dos arreglos de 2 dimensiones que solo contengan enteros aleatoriamente 
K = np.random.randint(low=2,high=50,size=(2,2))
print('K=')
print(K)
print()
print('M=')
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

K=
[[ 7 14]
 [30 32]]

M=
[[24 39]
 [38 33]]


In [0]:
# Concatenación vertical

#Forma 1
VS=np.vstack((K,M))

#Forma 2 
VS2=np.concatenate([K, M], axis = 0)


print('Concatenado vertical')
print(VS)
print()
print(VS2)

Concatenado vertical
[[ 7 14]
 [30 32]
 [24 39]
 [38 33]]

[[ 7 14]
 [30 32]
 [24 39]
 [38 33]]


In [0]:
# Concatenación horizontal

#Forma 1
VH=np.hstack((K,M))

#Forma 2 
VH2=np.concatenate([K, M.T], axis = 1)

print('Concatenado horizontal')
print(VH)
print()
print(VH2)

Concatenado horizontal
[[ 7 14 24 39]
 [30 32 38 33]]

[[ 7 14 24 38]
 [30 32 39 33]]


#### 2.3.6 Broadcasting 

Una de las ventajas que nos ofrece numpy es poder operar elementos de arreglos de diferentes tamaños y esto se llama broadcasting. 

Para mayor información: https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [0]:
A = np.zeros((4,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
#Suma en cada fila los elementos del vector 

print('Vector renglon VR',np.array([2,4,1]))
print()
print('Operacion A+VR ')
print(A+np.array([2,3,1]))
print()


#Ahora suma las columnas
print('Vector columna VC')
print(np.array([[2],[3],[1],[0]]))
print()
print('Operacion A+VC ')
print(A+np.array([[2],[3],[1],[0]]))


Vector renglon VR [2 4 1]

Operacion A+VR 
[[2. 3. 1.]
 [2. 3. 1.]
 [2. 3. 1.]
 [2. 3. 1.]]

Vector columna VC
[[2]
 [3]
 [1]
 [0]]

Operacion A+VC 
[[2. 2. 2.]
 [3. 3. 3.]
 [1. 1. 1.]
 [0. 0. 0.]]
Vector columna VC
[[2 1]
 [3 1]
 [1 1]
 [0 1]]

Operacion A+VC 


ValueError: ignored

#### 2.3.7 Funciones universales
 
 Son todas aquellas funciones típicas encontradas en las operaciones matemáticas
 
* **Operaciones matemáticas básicas:**  Suma de elementos, producto de elementos, redondeo, divisiones, logaritmos, raices, exponentes, signo, etc.  

* **Funciones tringonométricas:** seno, coseno, tangente, funciones hiperbólicas, etc

* **Funciones lógicas:** and, or, xor, not, etc. 

* **Comparaciones: **  mayor que, menor que, igual que, etc. 
  
  
  Para mayor información: https://docs.scipy.org/doc/numpy-1.14.0/reference/ufuncs.html#available-ufuncs  

In [0]:
# Usamos el arreglo A de la sección anterior para realizar unos ejemplos

#Funcion suma 
print('sum(A) ',sum(A)) 
print()

#Función add
print('np.add(A,B)=', np.add(A,B))
print()

#Función seno
print('np.sin(A)=', np.sin(A))
print()

sum(A)  45

np.add(A,B)= [ 2  4  6  8 10 12 14 16 18 20]

np.sin(A)= [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]



#### 2.3.8 Generadores de números aleatorios




In [0]:
#Arreglos de números aleatorios uniformemente distribuidos
W=np.random.uniform(size=4)
print(W)

[0.70641044 0.20459577 0.50521986 0.12017045]


In [0]:
# Arreglos de números aleatorios normalmente distribuidos
Y = np.random.normal(size = (3,5))
print(Y)

[[-1.32147243  0.50209531 -1.27281132  0.62207289  0.02758637]
 [-1.67093003 -0.4016331  -1.989037   -0.04363416 -0.6906181 ]
 [-0.3911225   1.10057098 -0.30995523  0.36573378  0.90560696]]


In [0]:
# Arreglos de números enteros aleatorios 
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[12 48 25 44]


In [0]:
# Permutación para de un arreglo 
print(np.random.permutation(Z))

[25 48 12 44]


# 3. Sección de ejercicios a realizar 

##3.1 Ejercicios

1.   Crea un vector con 100 números aleatorios comprendidos entre el -1 y 1
2.   Crea un vector que multiplique por 10 cada elemento del vector creado en el ejercicio 1.
3.   Crea una matriz que tenga 10 filas y 10 columnas con 100 números aleatorios entre -1 y 1.
4.   Imprime la tercer columna de la matriz creada en el ejercicio 3.
5.   Imprime la media de la tercer columna de la matriz creada en el ejercicio 3.
6.   Imprime el valor máximo y mínimo de la 8 columna de la matriz creada en el ejercicio 3.
7.   Crea un vector del 1 al 5 y eleva a la potencia 3 cada elemento.
8.   Resolver un sistema de ecuaciones lineales (buscar ejemplo y ejercicio)
9.   Calcular el producto punto de los siguientes dos vectores: [1,2,3] [3,2,1]

## 3.2 Soluciones 



### 3.2.1 Crea un vector con 100 números aleatorios comprendidos entre el -1 y 1

In [0]:
A1=np.random.normal(size=100)
print(A1[:5])
print()
print(len(A1))


[-0.78855056 -2.59323814 -2.19085191 -0.26717596 -0.07884783]

100


### 3.2.2 Crea un vector que multiplique por 10 cada elemento del vector creado en el ejercicio 1.

In [0]:
A2=10*A1
print(A2[:5])

[ -7.88550562 -25.93238142 -21.90851913  -2.67175962  -0.78847829]


### 3.2.3 Crea una matriz que tenga 10 filas y 10 columnas con 100 números aleatorios entre -1 y 1.


In [0]:
A3=np.random.normal(size=(10,10))
A3.shape

print(A3)

[[ 0.56256407  2.39269303 -0.01481329 -0.0649714   0.40935984  2.39189364
   0.59636807  2.87922569  0.45382034  1.83988006]
 [-1.66494059 -0.55091806  1.50350574 -2.02228401 -1.22707304  0.06744955
  -1.45106437 -0.18440636  2.27396547  0.2649004 ]
 [-0.92992706  0.74055108  1.00099751 -1.44864851 -0.63658592 -1.33462466
  -1.5514507   0.84993345 -0.16969638 -0.86488387]
 [-1.17008844 -0.4096122  -0.89488952 -0.938167   -0.52219353  1.10532256
   1.07074755  0.18203776 -0.02294329  1.14777681]
 [-0.05875008  0.49255054  0.18988494 -0.70498836 -0.19363782  0.53149152
   0.51957015  1.00647347 -1.00478025 -0.95699593]
 [ 0.29883688 -0.01807091 -0.53321065  1.06506193 -0.03111142  0.6287392
  -0.20610385  0.86492318 -0.17666259 -0.79621265]
 [-1.72003061 -0.10737322  0.94011362  0.50314763  1.06579644 -0.3530597
   0.64931679  1.48988105  1.2831358  -0.32578192]
 [ 0.57283062 -0.24454137 -0.83145619 -0.20079264 -0.22228489 -1.32705268
  -0.6891082  -1.18525879 -0.16796458  1.33401162]
 [

### 3.2.4 Imprime la tercer columna de la matriz creada en el ejercicio 3.

In [0]:
print(A3[:,2])

[-0.01481329  1.50350574  1.00099751 -0.89488952  0.18988494 -0.53321065
  0.94011362 -0.83145619  0.15046659 -0.2898383 ]


### 3.2.5 Imprime la media de la tercer columna de la matriz creada en el ejercicio 3.

In [0]:
print(A3[:,2].mean())

0.12207604610826273


### 3.2.6 Imprime el valor máximo y mínimo de la 8 columna de la matriz creada en el ejercicio 3.

In [0]:
print('Máximo: ',np.amax(A3[:,7]))
print()
print('Mínimo: ',np.amin(A3[:,7]))

Máximo:  2.879225693329301

Mínimo:  -1.1852587853051408


### 3.2.7 Crea un vector del 1 al 5 y eleva a la potencia 3 cada elemento.

In [0]:
print(np.arange(1,6)**3)

[  1   8  27  64 125]


### 3.2.8 Manejo de números
  - Crea un arreglo del 0 al 99 
  - Dale forma para que sea 10x10 
  - Toma las primeras 6 columnas y 6 filas 
  - Obten los pares de la tercera fila y quinta fila 
  - La esquina inferior e izquierda
  

In [0]:
AA=np.arange(100)
print(AA)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [0]:
AA=AA.reshape(10,10)
print(AA)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [0]:
AA1=AA[:6,:6]
print(AA1)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [0]:
AA1[2::2,0::2]

array([[20, 22, 24],
       [40, 42, 44]])

### 3.2.8 Resolver un sistema de ecuaciones lineales (buscar ejemplo y ejercicio)

### 3.2.9 Calcular el producto punto de los siguientes dos vectores: [1,2,3] [3,2,1]

In [0]:
# 9.   Calcular el producto punto de los siguientes dos vectores: [1,2,3] [3,2,1]
c = np.array(a)
d = np.array(b)
#np.sum(c*d)
#(c*d).sum()
np.dot(c,d)
c.dot(d)
d.dot(c)

10

# 4. Conclusiones
* ¿Qué aprendieron?
* ¿Dónde lo pueden aplicar?

# 5. Referencias y material de interés


1.   [Python for Data Analysis](https://www.oreilly.com/library/view/python-for-data/9781491957653/)
2.   [Data Analysis with Python](https://www.coursera.org/learn/data-analysis-with-python)
3.   [Deep Learning Prerequisites: The Numpy Stack in Python](https://www.udemy.com/deep-learning-prerequisites-the-numpy-stack-in-python/)